version: '3.8'

services:
  api:
    command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn main:app --reload --host 0.0.0.0 --port 8081
    ports:
      - "8081:8081"
      - "5678:5678"
    volumes:
      - .:/app