version: '3.8'

services:
  api:
    build: .
    container_name: engine_api
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - db
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  worker:
    build: .
    container_name: engine_worker
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - db
    command: python consumer.py

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI

  db:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
